version: '3'
services:
  sgxwallet:
    image: skalenetwork/sgxwallet_sim:${SGX_WALLET_TAG}
    container_name: sgx-server
    restart: always
    network_mode: host
    ports:
      - "1026:1026"
      - "1027:1027"
      - "1028:1028"
      - "1029:1029"
    volumes:
      - ${SGX_DIR}:/usr/src/sdk/sgx_data:Z
      -  /dev/urandom:/dev/random
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "4"
    restart: unless-stopped
    command: -s -y

  redis:
    container_name: redis
    image: "redis:6.0-alpine"
    network_mode: host
    tty: true
    environment:
      - REDIS_REPLICATION_MODE=master
    command: "redis-server /config/redis.conf"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${REDIS_DATA_DIR}:/data/db:Z
      - ${REDIS_CONFIG_DIR}:/config:Z

        #   transaction-manager:
        #     container_name: skale_transaction-manager
        #     image: "transaction-manager:${TAG:-latest}"
        #     build:
        #       context: "."
        #       dockerfile: Dockerfile
        #     network_mode: host
        #     tty: true
        #     environment:
        #       SGX_SERVER_URL: ${SGX_SERVER_URL}
        #       SGX_CERTIFICATES_DIR_NAME: ${SGX_CERTIFICATES_DIR_NAME}
        #       ENDPOINT: ${ENDPOINT}
        #       NODE_DATA_PATH: /skale_node_data
        #       REDIS_URI: ${REDIS_URI}
        #     volumes:
        #       - ${SKALE_DIR}/node_data:/skale_node_data:Z

