version: '3'

services:
  sgx-server:
    image: skalenetwork/sgxwallet_sim:${SGX_WALLET_TAG}
    container_name: sgx-server
    restart: unless-stopped
    network_mode: host
    ports:
      - "1026:1026"
      - "1027:1027"
      - "1028:1028"
      - "1029:1029"
    volumes:
      - ${SGX_DIR}:/usr/src/sdk/sgx_data:Z
      -  /dev/urandom:/dev/random
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "4"
    command: -s -y

  redis:
    container_name: redis
    image: "redis:6.0-alpine"
    tty: true
    network_mode: host
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    command: "redis-server /config/redis.conf"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${REDIS_DATA_DIR}:/data/db:Z
      - ${REDIS_CONFIG_DIR}:/config:Z
