name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    env:
      ETH_PRIVATE_KEY: ${{ secrets.ETH_PRIVATE_KEY }}
      ENDPOINT: ${{ secrets.ENDPOINT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SGX_URL: ""

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update host dependencies
        run: sudo apt-get update --fix-missing

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install python dependencies
        run: |
          uv sync --prerelease=allow --all-extras
          uv pip install codecov

      - name: Checking formatting with ruff
        run: uv run ruff check

      - name: Mypy check
        run: uv run mypy transaction_manager

      - name: Run test containers
        run: ./scripts/run-test-containers.sh && sleep 60

      - name: Debug info
        run: docker ps -a && docker logs hnode --tail 500 && docker inspect hnode

      - name: Run unit tests
        run: ./scripts/run-tests.sh

      - name: Run functionality tests
        run: ./scripts/run-docker-tests.sh
